/* ============================================
   离线备用数据 — 当 Radio Browser API 不可达时使用
   ============================================ */

const FALLBACK = {
  // 热门发现页电台（精选可靠流地址）
  discover: [
    { stationuuid:'fb-001', name:'BBC World Service', tags:'news,world,english', country:'United Kingdom', countrycode:'GB', url:'http://stream.live.vc.bbcmedia.co.uk/bbc_world_service', url_resolved:'http://stream.live.vc.bbcmedia.co.uk/bbc_world_service', bitrate:128, favicon:'https://www.bbc.co.uk/favicon.ico' },
    { stationuuid:'fb-002', name:'KEXP 90.3 FM', tags:'indie,alternative,folk,world', country:'United States', countrycode:'US', url:'https://kexp-mp3-128.streamguys1.com/kexp128.mp3', url_resolved:'https://kexp-mp3-128.streamguys1.com/kexp128.mp3', bitrate:128, favicon:'https://www.kexp.org/favicon.ico' },
    { stationuuid:'fb-003', name:'SomaFM Groove Salad', tags:'ambient,chillout,lounge,electronic', country:'United States', countrycode:'US', url:'https://ice6.somafm.com/groovesalad-256-mp3', url_resolved:'https://ice6.somafm.com/groovesalad-256-mp3', bitrate:256, favicon:'https://somafm.com/img3/groovesalad-400.jpg' },
    { stationuuid:'fb-004', name:'Radio Paradise', tags:'rock,alternative,eclectic,world', country:'United States', countrycode:'US', url:'https://stream.radioparadise.com/mp-128', url_resolved:'https://stream.radioparadise.com/mp-128', bitrate:128, favicon:'https://www.radioparadise.com/favicon.ico' },
    { stationuuid:'fb-005', name:'FIP', tags:'jazz,world,electronic,pop,classical', country:'France', countrycode:'FR', url:'https://icecast.radiofrance.fr/fip-midfi.mp3', url_resolved:'https://icecast.radiofrance.fr/fip-midfi.mp3', bitrate:128, favicon:'https://www.fip.fr/favicon.ico' },
    { stationuuid:'fb-006', name:'France Inter', tags:'news,talk,french,culture', country:'France', countrycode:'FR', url:'https://icecast.radiofrance.fr/franceinter-midfi.mp3', url_resolved:'https://icecast.radiofrance.fr/franceinter-midfi.mp3', bitrate:128, favicon:'https://www.radiofrance.fr/favicon.ico' },
    { stationuuid:'fb-007', name:'Radio Swiss Jazz', tags:'jazz,smooth jazz', country:'Switzerland', countrycode:'CH', url:'https://stream.srg-ssr.ch/rjs/mp3_128.m3u8', url_resolved:'https://stream.srg-ssr.ch/rjs/mp3_128.m3u8', bitrate:128, favicon:'https://www.radioswissjazz.ch/favicon.ico' },
    { stationuuid:'fb-008', name:'Radio Swiss Classic', tags:'classical,orchestral', country:'Switzerland', countrycode:'CH', url:'https://stream.srg-ssr.ch/rsc/mp3_128.m3u8', url_resolved:'https://stream.srg-ssr.ch/rsc/mp3_128.m3u8', bitrate:128, favicon:'https://www.radioswissclassic.ch/favicon.ico' },
    { stationuuid:'fb-009', name:'SomaFM Illinois Street Lounge', tags:'lounge,jazz,easy listening,vintage', country:'United States', countrycode:'US', url:'https://ice6.somafm.com/illstreet-128-mp3', url_resolved:'https://ice6.somafm.com/illstreet-128-mp3', bitrate:128, favicon:'https://somafm.com/img3/illstreet-400.jpg' },
    { stationuuid:'fb-010', name:'SomaFM Drone Zone', tags:'ambient,space,electronic,atmospheric', country:'United States', countrycode:'US', url:'https://ice6.somafm.com/dronezone-256-mp3', url_resolved:'https://ice6.somafm.com/dronezone-256-mp3', bitrate:256, favicon:'https://somafm.com/img3/dronezone-400.jpg' },
    { stationuuid:'fb-011', name:'Antenne Bayern', tags:'pop,hits,german', country:'Germany', countrycode:'DE', url:'https://stream.antenne.de/antenne', url_resolved:'https://stream.antenne.de/antenne', bitrate:128, favicon:'https://www.antenne.de/favicon.ico' },
    { stationuuid:'fb-012', name:'Deutschlandradio Kultur', tags:'culture,classical,talk,german', country:'Germany', countrycode:'DE', url:'https://st01.sslstream.dlf.de/dlf/01/128/mp3/stream.mp3', url_resolved:'https://st01.sslstream.dlf.de/dlf/01/128/mp3/stream.mp3', bitrate:128, favicon:'https://www.deutschlandradio.de/favicon.ico' },
    { stationuuid:'fb-013', name:'BBC Radio 6 Music', tags:'alternative,indie,rock,pop,electronic', country:'United Kingdom', countrycode:'GB', url:'http://stream.live.vc.bbcmedia.co.uk/bbc_6music', url_resolved:'http://stream.live.vc.bbcmedia.co.uk/bbc_6music', bitrate:128, favicon:'https://www.bbc.co.uk/favicon.ico' },
    { stationuuid:'fb-014', name:'NTS Radio 1', tags:'eclectic,experimental,electronic,jazz,world', country:'United Kingdom', countrycode:'GB', url:'https://stream-relay-geo.ntslive.co.uk/stream', url_resolved:'https://stream-relay-geo.ntslive.co.uk/stream', bitrate:128, favicon:'https://www.nts.live/favicon.ico' },
    { stationuuid:'fb-015', name:'Radio Caprice Jazz', tags:'jazz,bebop,swing,blues', country:'Russia', countrycode:'RU', url:'http://79.120.39.202:9000/jazz', url_resolved:'http://79.120.39.202:9000/jazz', bitrate:128, favicon:'' },
    { stationuuid:'fb-016', name:'Venice Classic Radio', tags:'classical,opera,baroque,orchestra', country:'Italy', countrycode:'IT', url:'https://uk3.internet-radio.com/proxy/veniceradio?mp=/stream', url_resolved:'https://uk3.internet-radio.com/proxy/veniceradio?mp=/stream', bitrate:128, favicon:'' },
    { stationuuid:'fb-017', name:'SomaFM Beat Blender', tags:'electronic,house,deep house,dance', country:'United States', countrycode:'US', url:'https://ice6.somafm.com/beatblender-128-mp3', url_resolved:'https://ice6.somafm.com/beatblender-128-mp3', bitrate:128, favicon:'https://somafm.com/img3/beatblender-400.jpg' },
    { stationuuid:'fb-018', name:'Radio Nova', tags:'pop,rock,soul,funk,world', country:'France', countrycode:'FR', url:'https://novazz.ice.infomaniak.ch/novazz-128.mp3', url_resolved:'https://novazz.ice.infomaniak.ch/novazz-128.mp3', bitrate:128, favicon:'https://www.nova.fr/favicon.ico' },
    { stationuuid:'fb-019', name:'Classic FM', tags:'classical,orchestra,easy listening', country:'United Kingdom', countrycode:'GB', url:'http://media-ice.musicradio.com/ClassicFMMP3', url_resolved:'http://media-ice.musicradio.com/ClassicFMMP3', bitrate:128, favicon:'https://www.classicfm.com/favicon.ico' },
    { stationuuid:'fb-020', name:'Jazz FM UK', tags:'jazz,soul,blues,funk', country:'United Kingdom', countrycode:'GB', url:'http://edge-bauerne01.sharp-stream.com/jazz.mp3', url_resolved:'http://edge-bauerne01.sharp-stream.com/jazz.mp3', bitrate:128, favicon:'https://www.jazzfm.com/favicon.ico' }
  ],

  // 国家列表（从 COUNTRY_ZH 生成，stationcount 为估算值）
  countries: [
    {name:'United States',iso_3166_1:'US',stationcount:9000},{name:'Germany',iso_3166_1:'DE',stationcount:6000},
    {name:'United Kingdom',iso_3166_1:'GB',stationcount:4000},{name:'France',iso_3166_1:'FR',stationcount:3000},
    {name:'Brazil',iso_3166_1:'BR',stationcount:3000},{name:'Russia',iso_3166_1:'RU',stationcount:2500},
    {name:'Mexico',iso_3166_1:'MX',stationcount:2000},{name:'Italy',iso_3166_1:'IT',stationcount:2000},
    {name:'Spain',iso_3166_1:'ES',stationcount:1800},{name:'Poland',iso_3166_1:'PL',stationcount:1500},
    {name:'Netherlands',iso_3166_1:'NL',stationcount:1200},{name:'Australia',iso_3166_1:'AU',stationcount:1200},
    {name:'Canada',iso_3166_1:'CA',stationcount:1100},{name:'Argentina',iso_3166_1:'AR',stationcount:1000},
    {name:'Colombia',iso_3166_1:'CO',stationcount:900},{name:'Turkey',iso_3166_1:'TR',stationcount:900},
    {name:'India',iso_3166_1:'IN',stationcount:800},{name:'Japan',iso_3166_1:'JP',stationcount:800},
    {name:'Romania',iso_3166_1:'RO',stationcount:700},{name:'Portugal',iso_3166_1:'PT',stationcount:700},
    {name:'Austria',iso_3166_1:'AT',stationcount:600},{name:'Hungary',iso_3166_1:'HU',stationcount:600},
    {name:'Czech Republic',iso_3166_1:'CZ',stationcount:600},{name:'Greece',iso_3166_1:'GR',stationcount:550},
    {name:'Switzerland',iso_3166_1:'CH',stationcount:500},{name:'Belgium',iso_3166_1:'BE',stationcount:500},
    {name:'Sweden',iso_3166_1:'SE',stationcount:500},{name:'Chile',iso_3166_1:'CL',stationcount:450},
    {name:'Ukraine',iso_3166_1:'UA',stationcount:450},{name:'Bulgaria',iso_3166_1:'BG',stationcount:400},
    {name:'Peru',iso_3166_1:'PE',stationcount:400},{name:'South Korea',iso_3166_1:'KR',stationcount:350},
    {name:'Norway',iso_3166_1:'NO',stationcount:350},{name:'Denmark',iso_3166_1:'DK',stationcount:350},
    {name:'Finland',iso_3166_1:'FI',stationcount:300},{name:'Ireland',iso_3166_1:'IE',stationcount:300},
    {name:'South Africa',iso_3166_1:'ZA',stationcount:300},{name:'Indonesia',iso_3166_1:'ID',stationcount:280},
    {name:'Serbia',iso_3166_1:'RS',stationcount:280},{name:'Slovakia',iso_3166_1:'SK',stationcount:250},
    {name:'Croatia',iso_3166_1:'HR',stationcount:250},{name:'New Zealand',iso_3166_1:'NZ',stationcount:220},
    {name:'Ecuador',iso_3166_1:'EC',stationcount:200},{name:'Venezuela',iso_3166_1:'VE',stationcount:200},
    {name:'Philippines',iso_3166_1:'PH',stationcount:200},{name:'Israel',iso_3166_1:'IL',stationcount:200},
    {name:'Slovenia',iso_3166_1:'SI',stationcount:180},{name:'Uruguay',iso_3166_1:'UY',stationcount:180},
    {name:'Thailand',iso_3166_1:'TH',stationcount:160},{name:'Bolivia',iso_3166_1:'BO',stationcount:150},
    {name:'Morocco',iso_3166_1:'MA',stationcount:150},{name:'Egypt',iso_3166_1:'EG',stationcount:140},
    {name:'Lithuania',iso_3166_1:'LT',stationcount:140},{name:'Latvia',iso_3166_1:'LV',stationcount:120},
    {name:'Estonia',iso_3166_1:'EE',stationcount:120},{name:'Nigeria',iso_3166_1:'NG',stationcount:120},
    {name:'Paraguay',iso_3166_1:'PY',stationcount:110},{name:'Costa Rica',iso_3166_1:'CR',stationcount:100},
    {name:'Panama',iso_3166_1:'PA',stationcount:100},{name:'Dominican Republic',iso_3166_1:'DO',stationcount:100},
    {name:'Guatemala',iso_3166_1:'GT',stationcount:100},{name:'Singapore',iso_3166_1:'SG',stationcount:80},
    {name:'Malaysia',iso_3166_1:'MY',stationcount:80},{name:'Vietnam',iso_3166_1:'VN',stationcount:80},
    {name:'Taiwan',iso_3166_1:'TW',stationcount:80},{name:'United Arab Emirates',iso_3166_1:'AE',stationcount:70},
    {name:'Kazakhstan',iso_3166_1:'KZ',stationcount:70},{name:'Cuba',iso_3166_1:'CU',stationcount:70},
    {name:'Luxembourg',iso_3166_1:'LU',stationcount:60},{name:'Iceland',iso_3166_1:'IS',stationcount:60},
    {name:'Hong Kong',iso_3166_1:'HK',stationcount:60},{name:'China',iso_3166_1:'CN',stationcount:50},
    {name:'Pakistan',iso_3166_1:'PK',stationcount:50},{name:'Bangladesh',iso_3166_1:'BD',stationcount:40},
    {name:'Albania',iso_3166_1:'AL',stationcount:120},{name:'Bosnia and Herzegovina',iso_3166_1:'BA',stationcount:100},
    {name:'North Macedonia',iso_3166_1:'MK',stationcount:80},{name:'Moldova',iso_3166_1:'MD',stationcount:60},
    {name:'Georgia',iso_3166_1:'GE',stationcount:60},{name:'Armenia',iso_3166_1:'AM',stationcount:50},
    {name:'Azerbaijan',iso_3166_1:'AZ',stationcount:50},{name:'Belarus',iso_3166_1:'BY',stationcount:50},
    {name:'Kenya',iso_3166_1:'KE',stationcount:50},{name:'Ghana',iso_3166_1:'GH',stationcount:40},
    {name:'Saudi Arabia',iso_3166_1:'SA',stationcount:40},{name:'Lebanon',iso_3166_1:'LB',stationcount:40},
    {name:'Jordan',iso_3166_1:'JO',stationcount:30},{name:'Iran',iso_3166_1:'IR',stationcount:30},
    {name:'Puerto Rico',iso_3166_1:'PR',stationcount:100},{name:'El Salvador',iso_3166_1:'SV',stationcount:80},
    {name:'Honduras',iso_3166_1:'HN',stationcount:70},{name:'Nicaragua',iso_3166_1:'NI',stationcount:60},
    {name:'Jamaica',iso_3166_1:'JM',stationcount:40},{name:'Malta',iso_3166_1:'MT',stationcount:40},
    {name:'Cyprus',iso_3166_1:'CY',stationcount:40},{name:'Mongolia',iso_3166_1:'MN',stationcount:20}
  ],

  // 流派标签列表
  tags: [
    {name:'pop',stationcount:5440},{name:'music',stationcount:4543},{name:'rock',stationcount:2871},
    {name:'news',stationcount:2697},{name:'classical',stationcount:1561},{name:'jazz',stationcount:1093},
    {name:'dance',stationcount:1448},{name:'hits',stationcount:1363},{name:'oldies',stationcount:1286},
    {name:'80s',stationcount:1138},{name:'top 40',stationcount:930},{name:'public radio',stationcount:926},
    {name:'90s',stationcount:905},{name:'electronic',stationcount:897},{name:'christian',stationcount:888},
    {name:'adult contemporary',stationcount:870},{name:'classic rock',stationcount:838},
    {name:'pop rock',stationcount:811},{name:'community radio',stationcount:801},
    {name:'house',stationcount:698},{name:'country',stationcount:664},{name:'alternative',stationcount:640},
    {name:'folk',stationcount:553},{name:'70s',stationcount:539},{name:'variety',stationcount:460},
    {name:'metal',stationcount:409},{name:'soul',stationcount:394},{name:'chillout',stationcount:393},
    {name:'indie',stationcount:389},{name:'easy listening',stationcount:380},{name:'techno',stationcount:365},
    {name:'retro',stationcount:351},{name:'sports',stationcount:346},{name:'ambient',stationcount:332},
    {name:'religious',stationcount:328},{name:'disco',stationcount:321},{name:'culture',stationcount:317},
    {name:'lounge',stationcount:310},{name:'entertainment',stationcount:309},
    {name:'alternative rock',stationcount:309},{name:'gospel',stationcount:305},
    {name:'blues',stationcount:300},{name:'funk',stationcount:290},{name:'rap',stationcount:289},
    {name:'hiphop',stationcount:274},{name:'edm',stationcount:272},{name:'trance',stationcount:269},
    {name:'salsa',stationcount:261},{name:'latin pop',stationcount:259},{name:'smooth jazz',stationcount:242},
    {name:'world music',stationcount:245},{name:'eclectic',stationcount:237},{name:'mainstream',stationcount:235},
    {name:'hot adult contemporary',stationcount:234},{name:'reggae',stationcount:228},
    {name:'tropical',stationcount:228},{name:'hard rock',stationcount:227},
    {name:'university radio',stationcount:226},{name:'schlager',stationcount:214},
    {name:'relax',stationcount:213},{name:'deep house',stationcount:212},
    {name:'college radio',stationcount:210},{name:'cumbia',stationcount:204},
    {name:'hip-hop',stationcount:204},{name:'reggaeton',stationcount:203},
    {name:'rnb',stationcount:197},{name:'charts',stationcount:187},
    {name:'christmas music',stationcount:181},{name:'instrumental',stationcount:177},
    {name:'heavy metal',stationcount:173},{name:'pop dance',stationcount:167},
    {name:'soft rock',stationcount:155},{name:'adult hits',stationcount:155},
    {name:'chill',stationcount:155},{name:'r&b',stationcount:151},{name:'punk',stationcount:147},
    {name:'catholic',stationcount:147},{name:'classics',stationcount:141},
    {name:'romantic',stationcount:141},{name:'latin',stationcount:137},
    {name:'vallenato',stationcount:136},{name:'eurodance',stationcount:135}
  ]
};
